#!/usr/bin/env ruby
#
# Copyright (C) 2010 Marcelo E. Magallón <marcelo.magallon@gmail.com>
#
# This program is in the public domain.  To the extend permitted by
# applicable law I relinquish all my rights as copyright holder.  You
# are free to use, copy, modify and redistribute it as you see fit.

require 'rubygems'
require 'sequel'
require 'csv'

Sequel.connect('sqlite://padron.db') do |db|
    Dir.glob('TBL_*.csv').each do |file|
        table = file.sub(/.csv$/, '')
        puts ">>> #{table}"
        skip = true
        i = 0
        db.transaction do
            CSV.foreach(file) do |data|
                if i % 100 == 0
                    puts i
                end

                if skip
                    skip = false
                else
                    db[table.to_sym].insert(data)
                    i = i.succ
                end
            end
        end
    end
end
