#!/usr/bin/env ruby

require 'rubygems'
require 'sequel'

Sequel.connect('sqlite://padron.db') do |db|
    db.transaction do
        ds = db[:TBL_CENTROS_VOTACION]
        ARGF.each do |line|
            puts ">> #{line}"
            if line =~ /^\s*(\d+)\s+(.+\S)\s+(\d+)\s+(\d+)\s+(\D.+?)\s*$/
                m = Regexp.last_match
                a, b = m[3..4].map { |v| v.to_i }
                (a..b).each do |junta|
                    puts %Q{#{junta},"#{m[2]}","#{m[5]}"}
                    ds.insert(:JUNTA => junta.to_i, :DESCRIPCION => m[5])
                end
            else
                STDERR.puts "The hell? => #{line}"
            end
        end
    end
end
