#!/usr/bin/env ruby

require 'rubygems'
require 'sequel'
require 'tse'

def show_record(r)
    nombre = r.values_at(:NOMBRE, :PAPE, :SAPE).join(' ')
    printf " Persona: %s - %s\n", r[:CEDULA], nombre
    printf "   Junta: %s (%s)\n", r[:LOC], r[:JUNTA]
    printf "   Lugar: %s\n",
        r.values_at(:PROVINCIA, :CANTON, :DISTRITO).join(', ')
end

def show(q)
    i = 0
    q.each do |r|
        puts if i > 0
        show_record(r)
        i = i.succ
    end

    if i == 0
        puts "No se encontraron registros"
    end
end

TSE::run do |ds|
    while true do
        print ">> "

        line = STDIN.gets
        if line.nil?
            exit 0
        end

        line = line.chomp.gsub(/^\s+/, '').gsub(/\s+$/, '')
        r, what, search = TSE::query(ds, line)

        case r
        when :Q
            exit 0
        when nil
            puts "No entiendo la consulta"
        else
            label = case what
                    when :cedula : 'cédula'
                    when :nombre : 'nombre'
                    end
            puts "Buscando #{label} #{line} (#{search}) ..."
            show(r)
        end

        puts
    end
end
