#!/usr/bin/env ruby

require 'rubygems'
require 'sequel'

def show_record(r)
    nombre = r.values_at(:NOMBRE, :PAPE, :SAPE).join(' ')
    printf " Persona: %s - %s\n", r[:CEDULA], nombre
    printf "   Junta: %s (%s)\n", r[:LOC], r[:JUNTA]
    printf "   Lugar: %s\n",
        r.values_at(:PROVINCIA, :CANTON, :DISTRITO).join(', ')
end

def show(q)
    i = 0
    q.each do |r|
        puts if i > 0
        show_record(r)
        i = i.succ
    end

    if i == 0
        puts "No se encontraron registros"
    end
end

def deaccent(s)
    mapping = {
        'á' => 'A', 'é' => 'E', 'í' => 'I', 'ó' => 'O', 'ú' => 'U',
        'Á' => 'A', 'É' => 'E', 'Í' => 'I', 'Ó' => 'O', 'Ú' => 'U',
        'ü' => 'U', 'Ü' => 'U',
        'ñ' => 'Ñ',
        'ç' => 'C', 'Ç' => 'C',
    }

    n = s.clone

    mapping.each { |k, v| n.gsub!(k, v) }

    return n
end

def run
    Sequel.connect('sqlite://padron.db') do |db|
        ds = db[:TBL_PADRON].
            join(:TBL_JUNTAS, :NUM_JUNTA => :NUM_JUNTA).
            join(:TBL_CODELE_COMPLETO,
                 :COD_PROVINCIA => :TBL_JUNTAS__COD_PROVINCIA,
                 :COD_CANTON    => :TBL_JUNTAS__COD_CANTON,
                 :COD_DIST_ELEC => :TBL_JUNTAS__COD_DIST_ELEC).
            join(:TBL_CENTROS_VOTACION,
                 :JUNTA => :TBL_JUNTAS__NUM_JUNTA).
            select(:nombre,
                   :pape,
                   :sape,
                   :cedula,
                   :ediv_nombre_provincia.as(:PROVINCIA),
                   :ediv_nombre_canton.as(:CANTON),
                   :ediv_nombre_dist_elec.as(:DISTRITO),
                   :tbl_padron__num_junta.as(:JUNTA),
                   :tbl_centros_votacion__descripcion.as(:LOC)
                  ).
            order(:cedula)

        yield ds
    end
end

def build_where(ds, sym, q)
    q.include?('%') ? ds.where(sym.like(q)) : ds.where(sym => q)
end

def find_by_name(ds, nombre, pape, sape=nil)
    ds = build_where(ds, :NOMBRE, nombre)
    ds = build_where(ds, :PAPE, pape)
    unless sape.nil?
        ds = build_where(ds, :SAPE, sape)
    end

    ds
end

def query(ds, line)
    search = deaccent(line.upcase)

    case search
    when /^(\d+)[- ]+(\d+)[- ]+(\d+)$/

        n = "%d%04d%04d" % Regexp.last_match[1..3].map { |v| v.to_i }

        return ds.where(:CEDULA => n), :cedula, "#{n}"

    when /^\d+$/

        return ds.where(:CEDULA => search), :cedula, search

    when /^([^,]+),\s+(\S+)$/,
         /^(\S+)\s+(\S+)$/

        nombre, pape = Regexp.last_match[1..2]

        q = find_by_name(ds, nombre, pape)
        if q.count == 0
            q = find_by_name(ds, "%#{nombre}%", pape)
            if q.count == 0
                q = find_by_name(ds, "%#{nombre}%", "#{pape}%")
                if q.count == 0
                    q = find_by_name(ds, "%#{nombre}%", "%#{pape}%")
                end
            end
        end

        return q, :nombre, "#{nombre} #{pape}"

    when /^([^,]+),\s+([^,]+),\s+(\S+)$/,
         /^([^,]+),\s+(\S+)\s+(\S+)$/,
         /^(\S+)\s+(\S+)\s+(\S+)$/

        nombre, pape, sape = Regexp.last_match[1..3]

        q = find_by_name(ds, nombre, pape, sape)
        if q.count == 0
            q = find_by_name(ds, "%#{nombre}%", pape, sape)
            if q.count == 0
                q = find_by_name(ds,
                                 "%#{nombre}%",
                                 "#{pape}%",
                                 "#{sape}%")
                if q.count == 0
                    q = find_by_name(ds,
                                     "%#{nombre}%",
                                     "%#{pape}%",
                                     "%#{sape}%")
                end
            end
        end

        return q, :nombre, "#{nombre} #{pape} #{sape}"

    when "Q", "QUIT", "EXIT", "SALIR"
        return :Q

    else
        return nil
    end
end

run do |ds|
    while true do
        print ">> "

        line = STDIN.gets
        if line.nil?
            exit 0
        end

        line = line.chomp.gsub(/^\s+/, '').gsub(/\s+$/, '')
        r, what, search = query(ds, line)

        case r
        when :Q
            exit 0
        when nil
            puts "No entiendo la consulta"
        else
            label = case what
                    when :cedula : 'cédula'
                    when :nombre : 'nombre'
                    end
            puts "Buscando #{label} #{line} (#{search}) ..."
            show(r)
        end

        puts
    end
end
