#!/usr/bin/env ruby
#
# Copyright (C) 2010 Marcelo E. Magallón <marcelo.magallon@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301 USA.

require 'rubygems'
require 'sequel'
require 'tse'

def show_record(r)
    nombre = r.values_at(:NOMBRE, :PAPE, :SAPE).join(' ')
    printf " Persona: %s - %s\n", r[:CEDULA], nombre
    printf "   Junta: %s (%s)\n", r[:LOC], r[:JUNTA]
    printf "   Lugar: %s\n",
        r.values_at(:PROVINCIA, :CANTON, :DISTRITO).join(', ')
end

def show(q)
    i = 0
    q.each do |r|
        puts if i > 0
        show_record(r)
        i = i.succ
    end

    if i == 0
        puts "No se encontraron registros"
    end
end

TSE::run do |ds|
    while true do
        print ">> "

        line = STDIN.gets
        if line.nil?
            exit 0
        end

        line = line.chomp.gsub(/^\s+/, '').gsub(/\s+$/, '')
        r, what, search = TSE::query(ds, line)

        case r
        when :Q
            exit 0
        when nil
            puts "No entiendo la consulta"
        else
            label = case what
                    when :cedula : 'cédula'
                    when :nombre : 'nombre'
                    end
            puts "Buscando #{label} #{line} (#{search}) ..."
            show(r)
        end

        puts
    end
end
