#!/usr/bin/env ruby
#
# Copyright (C) 2010 Marcelo E. Magallón <marcelo.magallon@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301 USA.

require 'tse'
require 'erb'
require 'webrick'
include WEBrick

template = %q{
    <html>
        <head>
            <title>Consultas al padrón electoral</title>
        </head>
        <style>
            .odd { background-color: #EEE; }
            .even { background-color: #FFF; }
            .label { text-align: right; font-weight: bold; }
            table {
                border-collapse: collapse;
                border-spacing: 0;
                width: 80%;
                margin-left: auto;
                margin-right: auto;
            }
            td { padding: 3px; }
        </style>
        <body onload="document.f.q.focus()">
            <form name="f" action="/">
                <input type="text" name="q" size=60 value="">
                <input type="submit" value="Consultar">
            </form>
            <% if not r.nil? %>
                <% if r.count == 0 %>
                    <p>No se encontraron resultados</p>
                <% else %>
                    <table>
                    <% r.each do |row| %>
                        <%
                            nombre = row.
                                values_at(:NOMBRE, :PAPE, :SAPE).
                                join(' ')
                            junta = "#{row[:LOC]} (#{row[:JUNTA]})"
                            lugar = row.
                                values_at(:PROVINCIA, :CANTON, :DISTRITO).
                                join(', ')
                            color = i % 2 == 0 ? "even" : "odd"
                        %>
                        <tbody class="<%= color%>">
                            <tr>
                                <td class="label">Persona</td>
                                <td><%= "#{nombre} (#{row[:CEDULA]})" %></td>
                            </tr>
                            <tr>
                                <td class="label">Junta</td>
                                <td><%= junta %></td>
                            </tr>
                            <tr>
                                <td class="label">Lugar</td>
                                <td><%= lugar %></td>
                            </tr>
                        </tbody>
                        <% i = i+1 %>
                    <% end %>
                    </table>
                <% end %>
            <% end %>
        </body>
    </html>
}.gsub(/^    /, '')

TSE::run do |ds|
    root_proc = lambda do |req, resp|
      resp['Content-Type'] = "text/html"

      message = ERB.new(template)
      q, r, i = nil, nil, 0
      if req.query.has_key?('q')
          q = req.query['q'].gsub(/^\s+/, '').gsub(/\s+$/, '')
          r, what, search = TSE::query(ds, q)
      end

      resp.body = message.result(binding)
    end

    root = HTTPServlet::ProcHandler.new(root_proc)

    s = HTTPServer.new(:Port => 2000)

    s.mount("/", root)
    trap("INT"){ s.shutdown }
    s.start
end
