#!/usr/bin/env ruby
#
# Copyright (C) 2010 Marcelo E. Magallón <marcelo.magallon@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301 USA.

require 'tse'
require 'webrick'
include WEBrick

TSE::run do |ds|
    root_proc = lambda do |req, resp|
      resp['Content-Type'] = "text/html"

      result = ""
      i = 0
      if req.query.has_key?('q')
          q = req.query['q'].gsub(/^\s+/, '').gsub(/\s+$/, '')
          r, what, search = TSE::query(ds, q)
          if r.nil? or r.count == 0
              result = "No se encontraron resultados"
          else
              r.each do |row|
                  nombre = row.values_at(:NOMBRE, :PAPE, :SAPE).join(' ')
                  junta = "#{row[:LOC]} (#{row[:JUNTA]})"
                  lugar =
                      row.values_at(:PROVINCIA, :CANTON, :DISTRITO).join(', ')

                  color = i % 2 == 0 ? "even" : "odd"
                  result += %{<div class="#{color}">}
                  result += %{<p>Persona: #{nombre} (#{row[:CEDULA]})</p>}
                  result += %{<p>Junta: #{junta}</p>}
                  result += %{<p>Lugar: #{lugar}</p>}
                  result += %{</div>}

                  i = i+1
              end
          end
      end

      resp.body = %{
    <html>
    <style>
    .odd { background-color: #EEE; }
    .even { background-color: #FFF; }
    </style>
    <body onload="document.f.q.focus()">
        <form name="f" action="/">
            <input type="text" name="q" size=60 value="">
            <input type="submit" name="submit" value="Consultar">
        </form>
        #{result}
    </body></html>
      }
    end

    root = HTTPServlet::ProcHandler.new(root_proc)

    s = HTTPServer.new(:Port => 2000)

    s.mount("/", root)
    trap("INT"){ s.shutdown }
    s.start
end
